/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-office-automation.h
 #	source generated by 4D Plugin Wizard
 #	Project : office-automation
 #	author : miyako
 #	2021/05/19
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_OFFICE_AUTOMATION_H
#define PLUGIN_OFFICE_AUTOMATION_H

#include "4DPluginAPI.h"

#include "4DPlugin-JSON.h"

#pragma mark -

void office_automation(PA_PluginParameters params);

#if VERSIONMAC
#import "Excel.h"
#import "Word.h"
#endif

#if VERSIONWIN
#include "ExcelApplication.h"
#include "ExcelWorkbooks.h"
#include "ExcelWorkbook.h"
#include "WordApplication.h"
#include "WordDocuments.h"
#include "WordDocument.h"
#endif

typedef enum {
    
    office_command_none  = 0,
    office_command_close = 1,
    office_command_open  = 2
    
}office_command_t;

typedef enum {
    
    office_app_none    = 0,
    office_app_excel   = 1,
    office_app_word    = 2,
    office_app_outlook = 3
    
}office_app_t;

#endif /* PLUGIN_OFFICE_AUTOMATION_H */
